'use strict';

var $ = exports;

$.ANALOG_DEVICE_BUFFER_SIZE = 32;
$.ANALOG_DEVICE_NAME = '/dev/lms_analog';

$.ANALOG_ADC_REF = 5000; /* [mV] maximal value on ADC */
$.ANALOG_ADC_RES = 4095; /* [CNT] maximal count on ADC */
$.ANALOG_AMP_CIN = 22;   /* [Times] */
$.ANALOG_AMP_VIN = 0.5;  /* [Times] */
$.ANALOG_VCE = 0.05;     /* [V] */

$.ANALOG_BATTERY_CURRENT_OFFSET = 28;
$.ANALOG_CELL123456_OFFSET = 30;

$.MOTOR_DEVICE_BUFFER_SIZE = 48;
$.MOTOR_DEVICE_NAME = '/dev/lms_motor';

$.MOTOR_A_PORT = 0x01;
$.MOTOR_B_PORT = 0x02;
$.MOTOR_C_PORT = 0x04;
$.MOTOR_D_PORT = 0x08;

$.MOTOR_A_SPEED_OFFSET = 4;
$.MOTOR_B_SPEED_OFFSET = $.MOTOR_A_SPEED_OFFSET + 12;
$.MOTOR_C_SPEED_OFFSET = $.MOTOR_B_SPEED_OFFSET + 12;
$.MOTOR_D_SPEED_OFFSET = $.MOTOR_C_SPEED_OFFSET + 12;

$.MOTOR_A_TACHO_COUNT_OFFSET = 8;
$.MOTOR_B_TACHO_COUNT_OFFSET = $.MOTOR_A_TACHO_COUNT_OFFSET + 12;
$.MOTOR_C_TACHO_COUNT_OFFSET = $.MOTOR_B_TACHO_COUNT_OFFSET + 12;
$.MOTOR_D_TACHO_COUNT_OFFSET = $.MOTOR_C_TACHO_COUNT_OFFSET + 12;

$.PWM_DEVICE_NAME = '/dev/lms_pwm';

$.PWM_OUTPUT_CLR_COUNT = 0xB2;
$.PWM_OUTPUT_POLARITY = 0xA7;
$.PWM_OUTPUT_POWER = 0xA4;
$.PWM_OUTPUT_SPEED = 0xA5;
$.PWM_OUTPUT_START = 0xA6;
$.PWM_OUTPUT_STOP = 0xA3;

$.UI_DEVICE_BUFFER_SIZE = 6;
$.UI_DEVICE_NAME = '/dev/lms_ui';

$.UI_BUTTON_DEBOUNCE_TIME = 30; // TODO

$.UI_BUTTON_UP = 0;
$.UI_BUTTON_ENTER = 1;
$.UI_BUTTON_DOWN = 2;
$.UI_BUTTON_RIGHT = 3;
$.UI_BUTTON_LEFT = 4;
$.UI_BUTTON_ESCAPE = 5;
